#include <iostream>
#include <vector>
#include <cmath>
#include <fstream>
using namespace std;

class Shape {
public:
    double x; // has to be public
    double y; // has to be public
    Shape(double a, double b) : x(a), y(b) {}
    virtual void draw(ostream& s) = 0;
};

class Polygon : public Shape {
private:
    double R;
    int N;
    const double PI = 3.14159265359;
public:
    Polygon(double a, double b, double r, int n) : Shape(a, b), R(r), N(n) {}
    void draw(ostream&/* type */ s) {
        double theta01 = (this -> N - 2) * this -> PI / this -> N;
        double theta02 = theta01 / 2;
        double theta03 = this -> PI / 2 - theta02;
        double theta04 = this -> PI * 2 / this -> N;
        s << this -> x + this -> R * sin(theta03) << " " << this -> y - this -> R * cos(theta03) << " moveto" << endl;
        for (int i = 1; i < this -> N; i ++) {
            theta03 = theta04 + theta03;
            s << this -> x + this -> R * sin(theta03) << " " << this -> y - this -> R * cos(theta03) << " lineto" << endl;
        }
        s << "closepath" << endl;
        s << "stroke" << endl;
    } // generate a string
};

class FilledRect : public Shape {
private:
    double W;
    double H;
public:
    FilledRect (double a, double b, double w, double h) : Shape(a, b), W(w), H(h) {}
    void draw(ostream& s) {
        s << x << " " << y << " moveto" << endl; // set the origin
        s << x + this -> W << " " << y << " lineto" << endl; // draw the line
        s << x + this -> W << " " << y + this -> H << " lineto" << endl;
        s << x << " " << y + this -> H << " lineto" << endl;
        s << "closepath" << endl;
        s << "fill" << endl;
    }
};

class Rect : public Shape {
private:
    double W;
    double H;
public:
    Rect(double a, double b, double w, double h) : Shape(a, b), W(w), H(h) {}
    void draw(ostream& s) {
        s << x << " " << y << " moveto" << endl;
        s << x + this -> W << " " << y << " lineto" << endl;
        s << x + this -> W << " " << y + this -> H << " lineto" << endl;
        s << x << " " << y + this ->  H << " lineto" << endl;
        s << "closepath" << endl;
        s << "stroke" << endl;
    }
};

class FilledCircle : public Shape {
private:
    double R;
public:
    FilledCircle (double a, double b, double r) : Shape(a, b), R(r) {}
    void draw (ostream& s) {
        s << x << " " << y << " " << this -> R << " " << 0 << " " << 360 << " " << "arc fill" << endl;

    }
};

class Circle : public Shape {
private:
    double R;
public:
    Circle (double a, double b, double r) : Shape(a, b), R(r) {}
    void draw(ostream& s) {
        s << x << " " << y << " " << this -> R << " " << 0 << " " << 360 << " " << "arc stroke" << endl;
    }
};

class Line : public Shape {
private:
    double x1;
    double y1;
public:
    Line (double a, double b, double c, double d) : Shape(a, b), x1(c), y1(d) {}
    void draw (ostream& s) {
        s << x << " " << y << " " << "moveto" << endl;
        s << this -> x1 << " " << this -> y1 << " " << "lineto" << endl;
        s << "stroke" << endl;
    }
};

class Drawing {
private:
    // declare a object, type is ofstream
    ofstream f; // write date into the file
    // like an array
    vector<Shape*> shapes; // the type of shapes is a pointer and the type of pointer is Shape
    int numShapes;
public:
    double A;
    double B;
    double C;
    bool key = true;
    Drawing(string filename) : f(filename.c_str()), shapes() /* empty vector */ {}
    void add(Shape* s) {
        this -> shapes.push_back(s);
    }
    void draw() {
        this -> numShapes = this -> shapes.size();
        for (int i = 0; i < numShapes; i ++) {
            // f is a file,
            // f contains lines of string which are generated by draw function of the abstract class
            shapes[i] -> draw(f); // object to call the void draw

            if (i == 7) {
                f << A << " " << B << " " << C << " " << "setrgbcolor" << endl;
            }
        }
    }
    void setrgb(double a, double b, double c) {
        // f << write, f >> read
        A = a;
        B = b;
        C = c;
        if (key) {
            f << a << " " << b << " " << c << " " << "setrgbcolor" << endl;
            key = false;
        }
    }
};
int main() {
//     ofstream f(); // open the file
////    Drawing d("testcode.ps");
////    d.setrgb(1, 0, 0); // set drawing color to be bright red:  1 0 0 setrgbcolor
////    d.add(new FilledRect(100.0, 150.0, 200.0, 50)); // x y moveto x y lineto ... fill
////    d.add(new Rect(100.0, 150.0, 200.0, 50));       // x y moveto x y lineto ... stroke
////    for (int x = 0; x < 600; x += 100)
////        d.add(new FilledCircle(x,200,50.0)); // x y r 0 360 arc fill
////    d.setrgb(0, 1, 0); // the rest are green
////    d.add(new Circle(0,0, 100)); // 0 0 100 0 360 stroke
////    d.add(new Line(400, 500, 600, 550));
////    d.add(new Polygon(200, 200, 50, 6)); // r = 50, n = 6;
////    d.draw();
for(int i = 1; i < 20; i *=2){
 cout << i;
}
cout<< endl;
    for(int i = 100; i > 0; i = i / 3 - 1){
        cout << i;
    }
    cout<< endl;
}